# Generated by Django 4.1.3 on 2022-12-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=255, verbose_name='FirstName')),
                ('lastname', models.CharField(max_length=255, verbose_name='LastName')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('optintophystatements', models.IntegerField(max_length=1, verbose_name='OptIntoPhyStatements')),
            ],
        ),
    ]
