# Generated by Django 4.1.3 on 2022-12-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbstechtrek_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.IntegerField(default=1, max_length=200, verbose_name='UserID'),
            preserve_default=False,
        ),
    ]
